version: "3"
services:
  backend:
    image: himanshu1425/flaskapp:latest
    ports:
      - 5000:5000
    environment:
      MYSQL_USER: admin
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: admin
      MYSQL_DB: mydb
    depends_on:
      - mysql
  mysql:
    image: himanhsu1425/mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: admin
      MYSQL_DB: mydb
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
      - mysql-data:/var/lib/mysql
volumes:
  ? mysql-data
